title: Brandon Watts # your name (or website title) here
logo: "bwatts1069.github.io/images/Profile Picture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Dedicated and knowledgeable Marine Corps Veteran with ten years of work experience. Strong desire to produce quality work to meet organizational goals and achieve business success. Capable of working alone and as a member of a team. Comfortable taking the initiative to solve complex problems as they arise in an ever-changing work environment. 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
